all: exclusive primesum endtime

exclusive: exclusive.cpp
	g++ -Wall -pedantic-errors -o exclusive exclusive.cpp

primesum: primesum.cpp
	g++ -Wall -pedantic-errors -o primesum primesum.cpp

endtime: endtime.cpp
	g++ -Wall -pedantic-errors -o endtime endtime.cpp

clean:
	rm -f exclusive
	rm -f primesum
	rm -f endtime
